### ISSUE TITLE
从solo数据库迁移bolo问题

### ISSUE THREAD

**Issue by zhangfeibiao** [adlered/bolo-solo#103]
`articleCommentCount` int(11) NOT NULL COMMENT '文章评论计数',
`articleViewCount` int(11) NOT NULL COMMENT '文章浏览计数',
`articleCommentable` char(1) NOT NULL COMMENT '文章是否可以评论'

字段在solo博客库b3_solo_article表中是没有的，直接迁移会报错Unknown column 'articleCommentCount' in 'order clause'

**Comment by adlered** [comment]
问题已收到。Solo更新后移除了该数据表，后续会进行处理。

**Comment by adlered** [comment]
新版 Bolo 会推出快速迁移工具，感谢你的建议，我们下个版本见 :)

**Comment by adlered** [comment]
请关注 Issue #96 ，先关闭这个 Issue 啦。

**Comment by zhangfeibiao** [comment]
好的👍
