### ISSUE TITLE
文章排序规则能否增加按创建时间排序

### ISSUE THREAD

**Issue by zhangfeibiao** [adlered/bolo-solo#111]
偶然发现之前的文章有错别字，或者有描述不对的地方，这种情况要对其进行编辑调整
但是改完后，该文章在博客前台页面上排在了前面，并不是很想这样
能否增加一个可选的排序规则，可以选择根据创建时间排序

**Comment by adlered** [comment]
请更新V2.2后（现在还没有，等几天哦）在 `偏好设定-参数设置`取消勾选`主页以文章更新日期排序`
