### ISSUE TITLE
文章时间显示问题

### ISSUE THREAD

**Issue by zhangfeibiao** [adlered/bolo-solo#112]
目前文章显示的都是更新时间，对于读者查看应该会有些误解

希望能把创建时间体现出来

如果一定要体现更新时间的话，可以增加类似「最后修改：」文案标注

**Comment by adlered** [comment]
感谢你的提议，V2.2版本将会直接显示创建日期，隐藏掉更新日期，并默认按创建时间进行主页文章的排序，再三思考下这种逻辑也是最符合常人的，请期待V2.2版本发布哦
