### ISSUE TITLE
密码加密存储

### ISSUE THREAD

**Issue by kangaroo1122** [AdlerED/bolo-solo#12]
StringBuffer sb = new StringBuffer(32);
        try {
            MessageDigest messageDigest = MessageDigest.getInstance("MD5");
            byte[] array = messageDigest.digest((username + password).getBytes(StandardCharsets.UTF_8));
            for (byte b : array) {
                sb.append(Integer.toHexString((b & 0xFF) | 0x100).toUpperCase().substring(1, 3));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        password = sb.toString();

**Comment by AdlerED** [comment]
收到啦，在开发的时候已经考虑过密码加密存储了~
下个版本会“可选”加密，因为MD5加密后是固定的32位，所以可以同时兼容明文和MD5加密后的密码进行识别登录。
v1.0公测版本没有加入的原因首先是因为时间问题，其次为了方便大家进行迁移。
感谢你的测试~

**Comment by AdlerED** [comment]
先打开，留到下个版本做 :smile:

**Comment by kangaroo1122** [comment]
加油，大佬^_^

**Comment by AdlerED** [comment]
密码加密存储已写，等待 v1.1 版本即可
