### ISSUE TITLE
使用github的自动备份功能，README.md显示错误

### ISSUE THREAD

**Issue by BreakerSAMA** [adlered/bolo-solo#122]
使用gayhub的自动备份后 ，README的文章列表超链地址少了端口号
例：
我的文章地址：http://blog.skter.cn:1000/articles/2020/09/03/1599063245653.html
gayhub的README.md显示的地址：http://blog.skter.cn/articles/2020/09/03/1599063245653.html

端口号缺失~~

**Comment by adlered** [comment]
`Latkes.class:257`
```
        if (StringUtils.isNotBlank(port) && !"80".equals(port) && !"443".equals(port)) {
            serverBuilder.append(':').append(port);
        }
```
经核查没有问题哦，请您参考文档：[GitHub或社区备份地址为IP而不是域名？](https://doc.stackoverflow.wiki/web/#/7?page_id=170)
