### ISSUE TITLE
有关 “自建 lute 服务器” 的相关问题

### ISSUE THREAD

**Issue by Hanmengnan** [adlered/bolo-solo#141]
使用 “ bolo-docker ” 方式安装时：

使用docker方式部署的 Lute 服务器，

配置 “config.sh” 文件时，参照提示，Lute 的地址填写 "http://localhost:8249"  ,这样配置 Lute 不会生效

![image](https://user-images.githubusercontent.com/30918851/103119060-a581d280-46ac-11eb-95a3-e22b8b4f5827.png)

更改为 "http://公网IP:8249" Lute 服务生效

**Comment by adlered** [comment]
您好，该问题为Docker容器网络环境问题，如果您是Linux系统，可以尝试在docker run的参数添加 `--net=host`。
