### ISSUE TITLE
博客内中文搜索贴子出现乱码回显

### ISSUE THREAD

**Issue by MartyAlien** [adlered/bolo-solo#148]
来自[Imp](https://tanyajun.top/bolo)的反馈：
输入英文能正常搜素并返回结果：
![](https://pic-bucket-1304861547.cos.ap-guangzhou.myqcloud.com/imgs/20210302140010.png)
输入含中文的关键词就直接乱码：
![](https://pic-bucket-1304861547.cos.ap-guangzhou.myqcloud.com/imgs/20210302140207.png)

**Comment by adlered** [comment]
![image](https://user-images.githubusercontent.com/6754458/109745903-7a1ce600-7c0f-11eb-8f16-4cf7a4362d28.png)

你好，这边经过测试没有问题，请问下系统环境？

**Comment by MartyAlien** [comment]
服务器：腾讯云CVM-centOS7
JDK：1.8
mysql:5.7 utf8编码
中间件是tomcat7  utf-8编码

**Comment by adlered** [comment]
建议尝试用[https://github.com/adlered/bolo-docker](bolo-docker)镜像尝试一下。
