### ISSUE TITLE
又拍云图床无法上传图片

### ISSUE THREAD

**Issue by teahouse15** [adlered/bolo-solo#159]
在正确设置又拍云图床的情况下，无法上传图片

![](https://user-images.githubusercontent.com/56344447/110899110-7853d080-833b-11eb-9724-584baca1e6ee.png)

![](https://user-images.githubusercontent.com/56344447/110899134-86a1ec80-833b-11eb-8460-8a90ecfee73a.png)

**Comment by adlered** [comment]
收到
