### ISSUE TITLE
首页中点微信会弹出新的空页面

### ISSUE THREAD

**Issue by shenyi1772887891** [adlered/bolo-solo#176]
![image](https://user-images.githubusercontent.com/73176271/120057014-9b586b80-c072-11eb-87aa-af02c0f649d6.png)

看了html代码，里面绑定的点击函数是alert微信号，但是加入了target=‘_blank’，导致alert失效并显示新的空白页面。

**Comment by adlered** [comment]
问题已收到，谢谢 :)
