### ISSUE TITLE
mp4视频文件，显示问题

### ISSUE THREAD

**Issue by expoli** [adlered/bolo-solo#180]
后台上传mp4 视频文件时，bolo-butterfly、bolo-sakura 主题会出现视频预览大小问题。

如下图所示，大小已经超出文章内容区域，其它皮肤暂时没发现有相关问题

![S8 OGB78{1H3RA}PR 92R%A](https://user-images.githubusercontent.com/31023767/121111776-0dcf0580-c842-11eb-8dbb-558789a37fd0.png)

文章链接：https://expoli.tech/articles/2021/06/07/1623066136894.html

**Comment by adlered** [comment]
感谢反馈。

**Comment by adlered** [comment]
鱼哥，修好了，Issue关闭 :)
