### ISSUE TITLE
后台增加实用小工具

### ISSUE THREAD

**Issue by csfwff** [AdlerED/bolo-solo#19]
1. 一键清空分类
2. 一键清空评论
3. 评论用户信息修改
3. 一键清空用户（得保留自己，不过评论似乎有影响？评论单独存似乎没事）
4. 导入导出数据（目前h2有导出，没导入，MySQL似乎没必要？）

再评估一下，选择必要的再安排上

**Comment by AdlerED** [comment]
多谢建议，将在 v1.1 版本推出 :smile:
