### ISSUE TITLE
不支持htts

### ISSUE THREAD

**Issue by liuguofeng-java** [adlered/bolo-solo#205]
![image](https://user-images.githubusercontent.com/59218624/131607786-6deda671-088f-4e7f-8842-8a75b2f0bc0b.png)

不支持htts请求，http是可以的，但是以https方式部署就有一些文件访问不到

**Comment by liuguofeng-java** [comment]
以https方式部署，结果有一些文件还是使用http方式请求服务器

**Comment by adlered** [comment]
修改latke.properties，http改为https即可。
