### ISSUE TITLE
https://cdn.jsdelivr.net静态CDN加速站点经常加载缓慢

### ISSUE THREAD

**Issue by Suery** [adlered/bolo-solo#217]
https://cdn.jsdelivr.net静态CDN加速站点经常加载缓慢，导致博客访问加载慢，可否把静态CDN加速的https://cdn.jsdelivr.net换到国内的加速站点？

**Comment by FlashFeiFei** [comment]
直接打包进项目吧，不需要加速，我的服务器能看得住，不在乎这点流量，第一次慢也无所谓

**Comment by Suery** [comment]
> 直接打包进项目吧，不需要加速，我的服务器能看得住，不在乎这点流量，第一次慢也无所谓

怎么弄？
