### ISSUE TITLE
文章允许修改创建日期

### ISSUE THREAD

**Issue by csfwff** [adlered/bolo-solo#22]
RT

**Comment by geektomya** [comment]
这个需要怎么去修改文章的创建日期呢，没找到。。还有这个文章的展示是只要我一更新某篇文章再次发布后，就又会出现在所有文章的第一个，希望可以弄成就按创建时间展示

**Comment by AdlerED** [comment]
> 这个需要怎么去修改文章的创建日期呢，没找到。。还有这个文章的展示是只要我一更新某篇文章再次发布后，就又会出现在所有文章的第一个，希望可以弄成就按创建时间展示

文章是用时间戳存储的，在文章表内
按创建时间展示，只需要在设置-偏好设置中关闭“显示更新”就可以了 :smile:

**Comment by geektomya** [comment]
> > 这个需要怎么去修改文章的创建日期呢，没找到。。还有这个文章的展示是只要我一更新某篇文章再次发布后，就又会出现在所有文章的第一个，希望可以弄成就按创建时间展示
> 
> 文章是用时间戳存储的，在文章表内
> 按创建时间展示，只需要在设置-偏好设置中关闭“显示更新”就可以了

哦哦，好的！

**Comment by adlered** [comment]
从 v1.2 拖更到 v1.7，哈哈哈，closed
