### ISSUE TITLE
进程重启后无法连接 mysql

### ISSUE THREAD

**Issue by R136a1-X** [adlered/bolo-solo#222]
<img width="1802" alt="image" src="https://user-images.githubusercontent.com/44422693/170867241-e865d4ce-592d-4392-91e8-da3cfc40b763.png">

docker 重启后就一直报这个错误，没有改动任何东西，就只是重启了，请问是什么问题？

**Comment by adlered** [comment]
在我们使用MySQL8.0的，连接数据库会存在一定的问题
当提示。Public Key Retrieval is not allowed 错误的时候，我们可以在连接数据库的配置文件中加上
```
allowPublicKeyRetrieval=true
```
这样重新启动项目即可解决问题
