### ISSUE TITLE
从 v2.1 升级到 v2.6 之后无法查看文章详情页

### ISSUE THREAD

**Issue by R136a1-X** [adlered/bolo-solo#223]
<img width="532" alt="image" src="https://user-images.githubusercontent.com/44422693/170885448-4ff54f99-bba4-4d40-861c-c80f4ffcb4d5.png">

有很多这种错误，而且 lute http 也报错，render 失败啥的。

**Comment by R136a1-X** [comment]
请问是什么原因？如何修复？

**Comment by adlered** [comment]
麻烦加一下我的微信，1101635162
