### ISSUE TITLE
随机阅读和相关阅读的显示 bug

### ISSUE THREAD

**Issue by Owemshu** [adlered/bolo-solo#236]
当我在设置启用 ‘bolo-butterfly’ 这一款皮肤时，在博客文章内会出现随机阅读和相关阅读的显示 bug，具体显示如下：
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/76020212/223000345-1b878be3-c4dd-4b13-81bc-baae5549167e.png">
这个连接存在且可以正常跳转。
我目前使用 Docker 部署，已更新到 V2.6 版本，并已经尝试修改设置、重启容器均无效。目前解决办法是修改随机阅读和相关阅读显示条数为 0 以掩饰该问题。

**Comment by gakkiyomi** [comment]
什么显示bug呢，我没有遇到过 http://gakkiyomi.me/

**Comment by Owemshu** [comment]
> 什么显示bug呢，我没有遇到过 http://gakkiyomi.me/

这是我在你给出的博客网址中[随机选择的一篇](http://gakkiyomi.me/articles/2020/11/04/1604486047868.html)，同样出现了该问题，具体效果如下：
<img width="1466" alt="image" src="https://github.com/adlered/bolo-solo/assets/76020212/835af01d-7142-4f7b-829c-2c9202f6e51e">

考虑到不同网页下均有出现了该问题，我推测应该是本人的显示设备对该风格下的渲染异常导致链接文字转为背景色，造成无法查看的文字的错误。且目前在本设备上仍无法解决这个问题。
本人设备如下：
- MacBook Pro 16 2021 macOS Ventura 13.4(22F66)
出现问题的浏览器如下：
- Arc Browser Version 0.106.1 (39259) Chromium Engine Version 114.0.5735.45
- Chrome （已卸载）
- Safari 16.5

**Comment by gakkiyomi** [comment]
我在safri上试了 的确有问题，chrome没问题
