### ISSUE TITLE
自定义图床

### ISSUE THREAD

**Issue by YeFei572** [AdlerED/bolo-solo#24]
你好, 看到介绍说有自定义图床, 目前项目已经跑起来了,但是没有找到在哪儿定义图床地址和key等相关内容

**Comment by AdlerED** [comment]
请看上传后的图片 URL，有玄机呦

**Comment by AdlerED** [comment]
你好，并非自定义图床哈，而是可以单独设定 B3log Key，使用黑客派的图床。千牛云等图床的支持还在开发中 :smile:

**Comment by YeFei572** [comment]
期待中, 图床功能大概什么时候能上线呢?

**Comment by YeFei572** [comment]
墙裂请求快点开发图床啊。。。大佬

**Comment by YeFei572** [comment]
隔三岔五的过来看看这个需求。。哈哈

**Comment by AdlerED** [comment]
基本实现代码已经完成了，可以关注 TuChuang 分支

**Comment by AdlerED** [comment]
明天实现七牛云、阿里、又拍的自定义图床，想询问最新消息的话可以直接加我微信（签名档）

**Comment by AdlerED** [comment]
功能开发完毕，请升级体验！

**Comment by YeFei572** [comment]
是tuchuang分支吗？有没有合道master分支啊， 是还有别的功能一起吗？

**Comment by YeFei572** [comment]
没刷新， 我浏览器一直打开就是你这个仓库，哈哈

**Comment by AdlerED** [comment]
正常升级就可以了，已经更新到 v1.3 稳定版了

**Comment by YeFei572** [comment]
发现个问题，  2.9.8的solo库和bolo1.3的库结构一样， 这可咋整

**Comment by AdlerED** [comment]
呃... Bolo v1.3 基于 Solo 2.9.0，请看 README，直接迁移过去就行了
