### ISSUE TITLE
我想在导航栏新增主题要怎么设置

### ISSUE THREAD

**Issue by llllyyyy66661111** [adlered/bolo-solo#249]
![微信截图_20240108111356](https://github.com/adlered/bolo-solo/assets/136055569/271f49f1-b306-494d-8fe5-df2b9fb977dd)
比如我要这个加一些自己定义的标签，要怎么操作

**Comment by teahouse15** [comment]
这个是写在静态文件里的，你可以仿照他的格式添加你自定义的标签
![image](https://github.com/user-attachments/assets/68173e0e-c122-497b-a435-b7c1a20622e6)

**Comment by teahouse15** [comment]
在后台添加的主题在这个皮肤的更多
![image](https://github.com/user-attachments/assets/8b5d1ff2-21e7-45f1-ab60-88241703bafd)
