### ISSUE TITLE
发现一个小问题

### ISSUE THREAD

**Issue by geektomya** [AdlerED/bolo-solo#26]
删除一篇文章后，这篇文章对应的分类的文章数量（就是在分类中后面显示的那个数字）不会减少。

**Comment by geektomya** [comment]
还有一个比较难受的一点是，

**Comment by AdlerED** [comment]
非常感谢，稍后排查。

**Comment by AdlerED** [comment]
Issue 备注：由于 Catogory 表中 Cnt 计数只会在每次发布相关文章增长，而不会自动减法导致

**Comment by AdlerED** [comment]
问题已修复，将跟随下个版本同步更新，非常感谢你的探索~
