### ISSUE TITLE
启用配图后配图403

### ISSUE THREAD

**Issue by Zbuter** [AdlerED/bolo-solo#30]
配图403怎么解决。

**Comment by AdlerED** [comment]
用的是solo-bolo-nexmoe皮肤吗

**Comment by Zbuter** [comment]
任何皮肤都一样 就是直接局域网ip+端口可以正常访问， 但是用域名就403  使用了nginx

**Comment by Zbuter** [comment]
任何皮肤都一样 就是直接局域网ip+端口可以正常访问， 但是用域名就403&nbsp; 使用了nginx
&nbsp;

&nbsp;- &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; A summer breeze how to embrace#


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Adler Chan"<notifications@github.com&gt;; 
发送时间: 2020年2月29日(星期六) 晚上7:01
收件人: "AdlerED/bolo-solo"<bolo-solo@noreply.github.com&gt;; 
抄送: "Zbuter"<zbuter@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AdlerED/bolo-solo] 启用配图后配图403 (#30)




用的是solo-bolo-nexmoe皮肤吗

**Comment by AdlerED** [comment]
方便提供下博客的域名吗，因为用的是黑客派的图床，之前D哥加了校验，我试试，不行的话我联系D哥帮你看看网站是不是被ban了

**Comment by Zbuter** [comment]
> 方便提供下博客的域名吗，因为用的是黑客派的图床，之前D哥加了校验，我试试，不行的话我联系D哥帮你看看网站是不是被ban了

找到原因了  是我的域名原因。

**Comment by AdlerED** [comment]
好的，有问题欢迎再提Issue。
