### ISSUE TITLE
可以支持https嘛?

### ISSUE THREAD

**Issue by implistarry** [AdlerED/bolo-solo#36]
加了Https然后css样式啥的还是http,页面就乱了
![image](https://user-images.githubusercontent.com/13974907/76640478-f9428580-658a-11ea-98ca-0f7b37fcc969.png)

**Comment by AdlerED** [comment]
你好，修改latke.properties，http改成https就行了，不会操作加我微信1101635162

**Comment by implistarry** [comment]
那个我修改了  但是里面用到的css什么的还是http的

**Comment by AdlerED** [comment]
方便加个微信吗，远程操作一下

**Comment by AdlerED** [comment]
如果已经修改过https了，清除下浏览器缓存，用手机访问试试看。
