### ISSUE TITLE
首次测试问题记录

### ISSUE THREAD

**Issue by csfwff** [AdlerED/bolo-solo#4]
1. 管理员登录 用户名密码框未对齐
2. 迁移时，先去后台修改自己的b3key，清除原先的分类，可以不用进数据库修改数据
3. 后台密码未加密
4. 增加分类后，未刷新的情况下修改文章，分类中不会出现新加的分类，同时文章数量也不会更新
5. 前台文章显示分类
6. 增加新特性，随时切换回solo

**Comment by AdlerED** [comment]
感谢测试，稍后修改

**Comment by AdlerED** [comment]
1. 经测试，Chrome浏览器正常
2. 已修改README
3. 考虑到迁移的便利性，暂时使用明文存储（不会造成安全问题）
4. 非常感谢，已添加自动刷新代码
5. 已经增加显示标签功能
6. 暂以迁回 Solo 指导文档（README中）代替
