### ISSUE TITLE
vditor功能按钮的tip乱码，多个js文件中文都是乱码

### ISSUE THREAD

**Issue by 2512500960** [adlered/bolo-solo#44]
![image](https://user-images.githubusercontent.com/16852896/79839493-2898ad80-83e7-11ea-99dc-1a6044134389.png)

使用的tomcat部署，在windows上部署的。

**Comment by adlered** [comment]
感觉是编码问题，方便的话加个微信吧：1101635162

**Comment by 2512500960** [comment]
已通过在catallina.bat开头添加set "JAVA_OPTS=%JAVA_OPTS% %JSSE_OPTS%  -Dfile.encoding=UTF-8"来解决。这个问题应该是只在windows才上会出现的。
![image](https://user-images.githubusercontent.com/16852896/79937783-5df7d680-848d-11ea-9d39-b04c64719f3f.png)
![image](https://user-images.githubusercontent.com/16852896/79937793-66e8a800-848d-11ea-84e7-aef28ec81885.png)

**Comment by adlered** [comment]
非常感谢，我会加到官方的安装手册中

**Comment by adlered** [comment]
https://doc.stackoverflow.wiki/web/#/7?page_id=81
