### ISSUE TITLE
建议新加导入博客园 文章功能

### ISSUE THREAD

**Issue by marklove5102** [adlered/bolo-solo#45]
博客园 提供了 备份 迁移 功能 导出全部文章.可以用作导入 bolo-solo
文章太多手工转费时间.

**Comment by adlered** [comment]
感谢建议，敬请期待。

**Comment by marklove5102** [comment]
目前解决方案
https://github.com/a568972484/html_to_md
直接转md 然后自己手工发帖。。。哎 有点累的说（150一篇文章） 不能 浏览器拖传 自己发文章。。。

**Comment by adlered** [comment]
关联Issue #56

**Comment by adlered** [comment]
[backup_CNBlogs_BlogBackup_131_201802_202004.xml.zip](https://github.com/adlered/bolo-solo/files/4626326/backup_CNBlogs_BlogBackup_131_201802_202004.xml.zip)
