### ISSUE TITLE
使用 Bolo 驱动的博客增加小令童鞋

### ISSUE THREAD

**Issue by lzh984294471** [adlered/bolo-solo#51]
小令童鞋solo迁移bolo，麻烦在[使用 Bolo 驱动的博客](https://doc.stackoverflow.wiki/web/#/7?page_id=87)上面添加下

站点地址：https://www.zeekling.cn/

**Comment by adlered** [comment]
感谢投稿，已加入至 [使用 Bolo 驱动的博客](https://doc.stackoverflow.wiki/web/#/7?page_id=87) 中，欢迎使用，有问题我们随时交流 :smile:

**Comment by lzh984294471** [comment]
好的，感谢。
