### ISSUE TITLE
博客创建日期bug

### ISSUE THREAD

**Issue by lzh984294471** [adlered/bolo-solo#52]
今天solo博客迁移bolo博客，发现一个问题，就是博客的创建日期是由前段传过去的，就会导致文章的创建日期存在偏差的问题：
- 先编辑一篇老的博客，不要保存，跳转到其他管理页面
- 然后再点击发布文章，这时候文章的创建时间还会是上次编辑的文章的时间
- 写完文章发布之后就是老的博客的创建时间。

**Comment by adlered** [comment]
Pjax 的锅，刷新浏览器即可解决，感谢反馈~
