### ISSUE TITLE
建议 bolo-nexmoe 主题增加存档时间线页面 archives.html

### ISSUE THREAD

**Issue by weifengliaoluan** [adlered/bolo-solo#55]
[nexmoe.zip](https://github.com/adlered/bolo-solo/files/4591505/nexmoe.zip)

建议 bolo-nexmoe 主题增加存档时间线页面 archives.html
归档是有的但是，没法直接展开到每一天的时间线，超爱一整条完整的时间线
![image](https://user-images.githubusercontent.com/64952459/81269383-ce048000-907b-11ea-98f1-e4714bde6b9c.png)

**Comment by adlered** [comment]
安排，v1.8 更新。
