### ISSUE TITLE
建议加入导入

### ISSUE THREAD

**Issue by weifengliaoluan** [adlered/bolo-solo#56]
只有导出没有导入
建议加入导入，支持wordpress，typecho博客备份的格式
方便其他人跳槽过来
🤞

**Comment by adlered** [comment]
关联Issue #45

**Comment by adlered** [comment]
[20200507_43.249.193.55_5eb38fa689ba0.txt](https://github.com/adlered/bolo-solo/files/4626566/20200507_43.249.193.55_5eb38fa689ba0.txt)

http://forum.typecho.org/viewtopic.php?f=6&t=12079
http://forum.typecho.org/viewtopic.php?f=6&t=11985

**Comment by adlered** [comment]
typecho的编码有些复杂，下个版本搞，这个版本先支持博客园

**Comment by adlered** [comment]
暂时搁置哦，备份文件比较复杂
