### ISSUE TITLE
最新版本v1.8报错。

### ISSUE THREAD

**Issue by zeekling** [adlered/bolo-solo#79]
最新版本报空指针错误
![efe2cddd1862e097a43f7bb916c5cf70.png](https://img.zeekling.cn/images/2020/05/30/efe2cddd1862e097a43f7bb916c5cf70.png)

**Comment by adlered** [comment]
关联
https://github.com/adlered/bolo-solo/commit/e05272439a6585a219699252203ee62bd0045d9e
