### ISSUE TITLE
升级了一个版本，图床好像坏掉了

### ISSUE THREAD

**Issue by YeFei572** [adlered/bolo-solo#81]
![image](https://user-images.githubusercontent.com/26360338/83426659-14be7d80-a462-11ea-852e-6ad96c918fcf.png)
![image](https://user-images.githubusercontent.com/26360338/83426719-2acc3e00-a462-11ea-8ee9-bbd0b4d933e9.png)

**Comment by YeFei572** [comment]
用的是bolo-docker仓库升级的， 图床是又拍云

**Comment by adlered** [comment]
查实中

**Comment by adlered** [comment]
麻烦提供个微信号，我们联系一下
