### ISSUE TITLE
皮肤使用出错

### ISSUE THREAD

**Issue by Y-Siv** [adlered/bolo-solo#86]
1.启用一款皮肤。
2.另外一款皮肤使用预览。
3.打开调试模式，预览手机样式。
4.预览过后，皮肤状态没有改变，而皮肤被直接应用了。
![image](https://user-images.githubusercontent.com/32136546/83880381-9e778f00-a771-11ea-9610-6af32f10b572.png)
![image](https://user-images.githubusercontent.com/32136546/83880433-b3542280-a771-11ea-9b50-a5c41a5f87d4.png)

**Comment by adlered** [comment]
皮肤基于Cookie，为了方便预览。只会在当前电脑下保存预览状态，请尝试：
1. 清除 Cookie 中的 `skin` 参数
2. 更换其它浏览器测试

感谢你的反馈！
