### ISSUE TITLE
bolo-sakura显示问题

### ISSUE THREAD

**Issue by geektomya** [adlered/bolo-solo#87]
当个性签名和博客名过长时，当显示导航栏时候，两者会重合。图是如下：
正常时候：
![image](https://user-images.githubusercontent.com/34698026/84477315-01ad7800-acc2-11ea-9ce1-0c13447d3a03.png)
显示导航栏的时候
![image](https://user-images.githubusercontent.com/34698026/84477346-0d00a380-acc2-11ea-813e-6f9a20fad79d.png)

**Comment by adlered** [comment]
不太好修，我试试看哦

**Comment by adlered** [comment]
![image](https://user-images.githubusercontent.com/6754458/89702875-2ba8b100-d978-11ea-9045-730d7ac9c4f0.png)

样式已做修改，去除副标题
