### ISSUE TITLE
从 solo 迁移到 bolo 删表的问题

### ISSUE THREAD

**Issue by watchman1999** [adlered/bolo-solo#90]
我看迁移指南 (https://doc.stackoverflow.wiki/web/#/7?page_id=83) 的说明，要清空  `b3_solo_category` 和 `b3_solo_category_tag` 表，也就是说迁移完之后标签和分类数据会全部丢失？这部分是不是可以优化下？毕竟体验不太好。

**Comment by adlered** [comment]
这方面确实影响体验了，不过这是因为bolo将分类独立化了，也就是不依赖标签了，所以数据表结构有很大的变化。下个版本我会做优化，感谢谅解~
