### ISSUE TITLE
存档可修改

### ISSUE THREAD

**Issue by squansh** [adlered/bolo-solo#94]
fantastic存档的话能不能变成可修改的呢？
有时候可能几个月没写文章，
然后突然一个月写很多，
但是单独修改文章日期的话，存档的日期是改不了的,
就想把文章存档给改平均一些。

**Comment by adlered** [comment]
可以试着修改 `b3_solo_archivedate_article` 表的 `archiveDate_oId` 项为指定时间戳，`article_oId`即文章编号可以在 `b3_solo_article` 中找到。

**Comment by adlered** [comment]
暂时不考虑单独做该功能，如果修改中出现问题可以加用户群，私信群主（我
