### ISSUE TITLE
fantastic皮肤标签和存档无数据显示问题

### ISSUE THREAD

**Issue by Y-Siv** [adlered/bolo-solo#95]
分类、标签、存档在无数据的情况下，点击会存在显示问题。
![image](https://user-images.githubusercontent.com/32136546/87535785-a14b9500-c6ca-11ea-953b-cc35affb509a.png)
![image](https://user-images.githubusercontent.com/32136546/87535816-ac9ec080-c6ca-11ea-8d90-582837c737a5.png)
![image](https://user-images.githubusercontent.com/32136546/87535917-cfc97000-c6ca-11ea-8bec-614bb544b482.png)

**Comment by adlered** [comment]
这个问题v1.9已经修复了，麻烦更新后重试。
